sudo: false
language: python
python:
        - "2.7"
cache:
        directories:
                - $HOME/gcloud/

env:
        - DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=$TRAVIS_BUILD_DIR GCLOUD=$HOME/gcloud/google-cloud-sdk/bin CLOUDSDK_PYTHON_SITEPACKAGES=1 GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/credentials.json


before_install:
        #secrets
        openssl aes-256-cbc -K $encrypted_9a4798c88375_key -iv $encrypted_9a4798c88375_iv -in secrets.tar.enc -out secrets.tar -d
        tar xvf secrets.tar

        #Install gcloud
        - if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then
                mkdir -p $HOME/gcloud &&
                wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=$HOME/gcloud &&
                cd $HOME/gcloud &&
                tar xzf google-cloud-sdk.tar.gz &&
                printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh &&
                cd $TRAVIS_BUILD_DIR;
          fi

install:
        - printf 'y\n' | $GCLOUD/gcloud components update app
        - $GCLOUD/gcloud config set app/hosted_registry true

script:
        - $GCLOUD/gcloud preview app deploy . --remote --server=gcr.appengine.google.com
        - python test.py
